build:
command: ng build --configuration production
commandOrigin: config
publish: /opt/build/repo/dist/FYLE-ASSIGNMENT
publishOrigin: config
redirects:   - from: /*
status: 200
to: /index.html
redirectsOrigin: config